# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8e4895264067da518ae2c31f0a95cc88dbce5209583c193e76ffbbe36b4a065298e35ff50537f1c22cd21f2ab5da49de7680f55c035264259b10700708ea1a6

test:
  secret_key_base: 202281f0e3e5cda3300cb7447d77fd6d2bc9f2c033944a05c607217816060fe257d852bb1473c18f92413b07b8b989684ca0a4f9ffc50b904407c622429a5055

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
